export const DEFAULT_FONT_SIZE = {
  BUTTON_SIZE: 16,
  FONT_SIZE_REGULAR: 16,
  FONT_SIZE_MEDIUM: 20,
};

export const DEFAULT_COLOR = {
  WHITE: '#FFFFFF',
  BLACK: '#150D13',
  GREEN_LIGHT: '#FFFFFF',
  GREEN_MEDIUM: '#5DD669',
  GREEN_DARK: '#416D19',
};
